'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.18444
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SelectShapesAddin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на BeginX,BeginY,EndX,EndY.
        '''</summary>
        Friend ReadOnly Property _D_Endpoints() As String
            Get
                Return ResourceManager.GetString("_D_Endpoints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на RotationXAngle,RotationYAngle,RotationZAngle,RotationType,Perspective,DistanceFromGround,KeepTextFlat.
        '''</summary>
        Friend ReadOnly Property _D_Rotation_Properties() As String
            Get
                Return ResourceManager.GetString("_D_Rotation_Properties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на SmartTags.Row_1.X,SmartTags.Row_1.Y,SmartTags.Row_1.TagName,SmartTags.Row_1.XJustify,SmartTags.Row_1.YJustify,SmartTags.Row_1.DisplayMode,SmartTags.Row_1.ButtonFace,SmartTags.Row_1.Description,SmartTags.Row_1.Disabled.
        '''</summary>
        Friend ReadOnly Property Action_Tags() As String
            Get
                Return ResourceManager.GetString("Action_Tags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Actions.Row_1.Action,Actions.Row_1.Menu,Actions.Row_1.TagName,Actions.Row_1.ButtonFace,Actions.Row_1.SortKey,Actions.Row_1.Checked,Actions.Row_1.Disabled,Actions.Row_1.ReadOnly,Actions.Row_1.Invisible,Actions.Row_1.BeginGroup,Actions.Row_1.FlyoutChild.
        '''</summary>
        Friend ReadOnly Property Actions() As String
            Get
                Return ResourceManager.GetString("Actions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на ReflectionTrans,ReflectionSize,ReflectionDist,ReflectionBlur,GlowColor,GlowColorTrans,GlowSize,SoftEdgesSize,SketchSeed,SketchEnabled,SketchAmount,SketchLineWeight,SketchLineChange,SketchFillChange.
        '''</summary>
        Friend ReadOnly Property Additional_Effect_Properties() As String
            Get
                Return ResourceManager.GetString("Additional_Effect_Properties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на AlignLeft,AlignCenter,AlignRight,AlignTop,AlignMiddle,AlignBottom.
        '''</summary>
        Friend ReadOnly Property Alignment() As String
            Get
                Return ResourceManager.GetString("Alignment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на BevelTopType,BevelTopWidth,BevelTopHeight,BevelBottomType,BevelBottomWidth,BevelBottomHeight,BevelDepthColor,BevelDepthSize,BevelContourColor,BevelContourSize,BevelMaterialType,BevelLightingType,BevelLightingAngle.
        '''</summary>
        Friend ReadOnly Property Bevel_Properties() As String
            Get
                Return ResourceManager.GetString("Bevel_Properties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на ReplaceLockShapeData,ReplaceLockText,ReplaceLockFormat,ReplaceCopyCells.
        '''</summary>
        Friend ReadOnly Property Change_Shape_Behavior() As String
            Get
                Return ResourceManager.GetString("Change_Shape_Behavior", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Char.Font[1],Char.Color[1],Char.Style[1],Char.Case[1],Char.Pos[1],Char.FontScale[1],Char.Size[1],Char.DblUnderline[1],Char.Overline[1],Char.Strikethru[1],Char.DoubleStrikethrough[1],Char.RTLText[1],Char.UseVertical[1],Char.Letterspace[1],Char.ColorTrans[1],Char.AsianFont[1],Char.ComplexScriptFont[1],Char.LocalizeFont[1],Char.ComplexScriptSize[1],Char.LangID[1].
        '''</summary>
        Friend ReadOnly Property Character() As String
            Get
                Return ResourceManager.GetString("Character", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на command 1.
        '''</summary>
        Friend ReadOnly Property Command1_Label() As String
            Get
                Return ResourceManager.GetString("Command1_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Быстрый выбор.
        '''</summary>
        Friend ReadOnly Property Command2_Label() As String
            Get
                Return ResourceManager.GetString("Command2_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Выбор по ячейкам.
        '''</summary>
        Friend ReadOnly Property Command3_Label() As String
            Get
                Return ResourceManager.GetString("Command3_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Connections.X1,Connections.Y1,Connections.DirX[1],Connections.DirY[1],Connections.Type[1],Connections.D.
        '''</summary>
        Friend ReadOnly Property Connection_Points() As String
            Get
                Return ResourceManager.GetString("Connection_Points", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Controls.Row_1.X,Controls.Row_1.Y,Controls.Row_1.XDyn,Controls.Row_1.YDyn,Controls.Row_1.XCon,Controls.Row_1.YCon,Controls.Row_1.CanGlue,Controls.Row_1.Type,Controls.Row_1.Tip.
        '''</summary>
        Friend ReadOnly Property Controls() As String
            Get
                Return ResourceManager.GetString("Controls", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на TheData,TheText,EventDblClick,EventXFMod,EventDrop,EventMultiDrop.
        '''</summary>
        Friend ReadOnly Property Events() As String
            Get
                Return ResourceManager.GetString("Events", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на FillForegnd,FillBkgnd,FillPattern,ShdwForegnd,ShdwPattern,FillForegndTrans,FillBkgndTrans,ShdwForegndTrans,ShdwBkgndTrans,ShapeShdwType,ShapeShdwOffsetX,ShapeShdwOffsetY,ShapeShdwObliqueAngle,ShapeShdwScaleFactor,ShapeShdwBlur,ShapeShdwShow.
        '''</summary>
        Friend ReadOnly Property Fill_Format() As String
            Get
                Return ResourceManager.GetString("Fill_Format", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на FillGradientStops.GradientStopColor[1],FillGradientStops.GradientStopColorTrans[1],FillGradientStops.GradientStopPosition[1].
        '''</summary>
        Friend ReadOnly Property Fill_Gradient_Stops() As String
            Get
                Return ResourceManager.GetString("Fill_Gradient_Stops", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на ImgOffsetX,ImgOffsetY,ImgWidth,ImgHeight,ClippingPath.
        '''</summary>
        Friend ReadOnly Property Foreign_Image_Info() As String
            Get
                Return ResourceManager.GetString("Foreign_Image_Info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Geometry1.NoFill,Geometry1.NoLine,Geometry1.NoShow,Geometry1.NoSnap,Geometry1.NoQuickDrag,Geometry1.X1,Geometry1.Y1,Geometry1.A1,Geometry1.B1,Geometry1.C1,Geometry1.D1,Geometry1.E1.
        '''</summary>
        Friend ReadOnly Property Geometry() As String
            Get
                Return ResourceManager.GetString("Geometry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на GlueType,WalkPreference,BegTrigger,EndTrigger.
        '''</summary>
        Friend ReadOnly Property Glue_Info() As String
            Get
                Return ResourceManager.GetString("Glue_Info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на LineGradientDir,LineGradientAngle,FillGradientDir,FillGradientAngle,LineGradientEnabled,FillGradientEnabled,RotateGradientWithShape,UseGroupGradient.
        '''</summary>
        Friend ReadOnly Property Gradient_Properties() As String
            Get
                Return ResourceManager.GetString("Gradient_Properties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на SelectMode,DisplayMode,IsDropTarget,IsSnapTarget,IsTextEditTarget,DontMoveChildren.
        '''</summary>
        Friend ReadOnly Property Group_Properties() As String
            Get
                Return ResourceManager.GetString("Group_Properties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Hyperlink.Row_1.Description,Hyperlink.Row_1.Address,Hyperlink.Row_1.SubAddress,Hyperlink.Row_1.ExtraInfo,Hyperlink.Row_1.Frame,Hyperlink.Row_1.NewWindow,Hyperlink.Row_1.Default,Hyperlink.Row_1.Invisible,Hyperlink.Row_1.SortKey.
        '''</summary>
        Friend ReadOnly Property Hyperlinks() As String
            Get
                Return ResourceManager.GetString("Hyperlinks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Gamma,Contrast,Brightness,Sharpen,Blur,Denoise,Transparency.
        '''</summary>
        Friend ReadOnly Property Image_Properties() As String
            Get
                Return ResourceManager.GetString("Image_Properties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на LayerMember.
        '''</summary>
        Friend ReadOnly Property Layer_Membership() As String
            Get
                Return ResourceManager.GetString("Layer_Membership", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на LineWeight,LineColor,LinePattern,Rounding,EndArrowSize,BeginArrow,EndArrow,LineCap,BeginArrowSize,LineColorTrans,CompoundType.
        '''</summary>
        Friend ReadOnly Property Line_Format() As String
            Get
                Return ResourceManager.GetString("Line_Format", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на LineGradientStops.GradientStopColor[1],LineGradientStops.GradientStopColorTrans[1],LineGradientStops.GradientStopPosition[1].
        '''</summary>
        Friend ReadOnly Property Line_Gradient_Stops() As String
            Get
                Return ResourceManager.GetString("Line_Gradient_Stops", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на NoObjHandles,NonPrinting,NoCtlHandles,NoAlignBox,UpdateAlignBox,HideText,DynFeedback,ObjType,Comment,IsDropSource,NoLiveDynamics,LocalizeMerge,NoProofing,Calendar,LangID,DropOnPageScale.
        '''</summary>
        Friend ReadOnly Property Miscellaneous() As String
            Get
                Return ResourceManager.GetString("Miscellaneous", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Copyright,HelpTopic,ShapeKeywords,ShapeTabStop.
        '''</summary>
        Friend ReadOnly Property Other_Сells() As String
            Get
                Return ResourceManager.GetString("Other_Сells", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Para.IndFirst[1],Para.IndLeft[1],Para.IndRight[1],Para.SpLine[1],Para.SpBefore[1],Para.SpAfter[1],Para.HorzAlign[1],Para.Bullet[1],Para.BulletStr[1],Para.BulletFont[1],Para.BulletFontSize[1],Para.TextPosAfterBullet[1],Para.Flags[1].
        '''</summary>
        Friend ReadOnly Property Paragraph() As String
            Get
                Return ResourceManager.GetString("Paragraph", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на LockWidth,LockHeight,LockMoveX,LockMoveY,LockAspect,LockDelete,LockBegin,LockEnd,LockRotate,LockCrop,LockVtxEdit,LockTextEdit,LockFormat,LockGroup,LockCalcWH,LockSelect,LockCustProp,LockFromGroupFormat,LockThemeColors,LockThemeEffects,LockThemeConnectors,LockThemeFonts,LockThemeIndex,LockReplace,LockVariation.
        '''</summary>
        Friend ReadOnly Property Protection() As String
            Get
                Return ResourceManager.GetString("Protection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на QuickStyleLineColor,QuickStyleFillColor,QuickStyleShadowColor,QuickStyleFontColor,QuickStyleLineMatrix,QuickStyleFillMatrix,QuickStyleEffectsMatrix,QuickStyleFontMatrix,QuickStyleType,QuickStyleVariation.
        '''</summary>
        Friend ReadOnly Property Quick_Style() As String
            Get
                Return ResourceManager.GetString("Quick_Style", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot; onLoad=&quot;OnRibbonLoad&quot;&gt;
        '''  &lt;ribbon&gt;
        '''    &lt;tabs&gt;
        '''      &lt;tab idMso=&quot;TabHome&quot;&gt;
        '''        &lt;group id=&quot;Group1&quot; label=&quot;SelectShapes&quot;&gt;
        '''
        '''          &lt;!--&lt;button id=&quot;Command1&quot; size=&quot;large&quot; getLabel=&quot;OnGetRibbonLabel&quot; onAction=&quot;OnRibbonButtonClick&quot; getEnabled=&quot;IsRibbonCommandEnabled&quot; getImage=&quot;GetRibbonImage&quot; /&gt;--&gt;
        '''          &lt;button id=&quot;Command2&quot; size=&quot;large&quot; getLabel=&quot;OnGetRibbonLabel&quot; onAction=&quot;OnRibbonButt [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property Ribbon() As String
            Get
                Return ResourceManager.GetString("Ribbon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Scratch.X1,Scratch.Y1,Scratch.A1,Scratch.B1,Scratch.C1,Scratch.D1.
        '''</summary>
        Friend ReadOnly Property Scratch() As String
            Get
                Return ResourceManager.GetString("Scratch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Prop.Row_1.Value,Prop.Row_1.Prompt,Prop.Row_1.Label,Prop.Row_1.Format,Prop.Row_1.SortKey,Prop.Row_1.Type,Prop.Row_1.Invisible,Prop.Row_1.Ask,Prop.Row_1.LangID,Prop.Row_1.Calendar.
        '''</summary>
        Friend ReadOnly Property Shape_Data() As String
            Get
                Return ResourceManager.GetString("Shape_Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на ShapePermeableX,ShapePermeableY,ShapePermeablePlace,Relationships,ShapeFixedCode,ShapePlowCode,ShapeRouteStyle,ShapePlaceStyle,ConFixedCode,ConLineJumpCode,ConLineJumpStyle,ConLineJumpDirX,ConLineJumpDirY,ShapePlaceFlip,ConLineRouteExt,ShapeSplit,ShapeSplittable,DisplayLevel.
        '''</summary>
        Friend ReadOnly Property Shape_Layout() As String
            Get
                Return ResourceManager.GetString("Shape_Layout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на PinX,PinY,Width,Height,LocPinX,LocPinY,Angle,FlipX,FlipY,ResizeMode.
        '''</summary>
        Friend ReadOnly Property Shape_Transform() As String
            Get
                Return ResourceManager.GetString("Shape_Transform", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на 1-D Endpoints,Action Tags,Actions,Alignment,Character,Connection Points,Controls,Events,Fill Format,Foreign Image Info,Geometry,Glue Info,Group Properties,Hyperlinks,Image Properties,Layer Membership,Line Format,Miscellaneous,Paragraph,Protection,Scratch,Shape Data,Shape Layout,Shape Transform,Tabs,Text Block Format,Text Fields,Text Transform,User-Defined Cells,Other Сells.
        '''</summary>
        Friend ReadOnly Property ShapeSheet14() As String
            Get
                Return ResourceManager.GetString("ShapeSheet14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на 1-D Endpoints,3-D Rotation Properties,Action Tags,Actions,Additional Effect Properties,Alignment,Bevel Properties,Change Shape Behavior,Character,Connection Points,Controls,Events,Fill Format,Fill Gradient Stops,Foreign Image Info,Geometry,Glue Info,Gradient Properties,Group Properties,Hyperlinks,Image Properties,Layer Membership,Line Format,Line Gradient Stops,Miscellaneous,Other Сells,Paragraph,Protection,Quick Style,Scratch,Shape Data,Shape Layout,Shape Transform,Tabs,Text Block Format,Text Fields,Text T [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property ShapeSheet15() As String
            Get
                Return ResourceManager.GetString("ShapeSheet15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на EnableLineProps,EnableFillProps,EnableTextProps,HideForApply.
        '''</summary>
        Friend ReadOnly Property Style_Properties() As String
            Get
                Return ResourceManager.GetString("Style_Properties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Tabs.Y1,Tabs.A1,Tabs.C1,Tabs.D1,Tabs.F1,Tabs.G1,Tabs.I1,Tabs.J1.
        '''</summary>
        Friend ReadOnly Property Tabs() As String
            Get
                Return ResourceManager.GetString("Tabs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на LeftMargin,RightMargin,TopMargin,BottomMargin,VerticalAlign,TextBkgnd,DefaultTabstop,TextDirection,TextBkgndTrans.
        '''</summary>
        Friend ReadOnly Property Text_Block_Format() As String
            Get
                Return ResourceManager.GetString("Text_Block_Format", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Fields.Value[1],Fields.Format[1],Fields.Type[1],Fields.UICat[1],Fields.UICod[1],Fields.UIFmt[1],Fields.Calendar[1],Fields.ObjectKind[1].
        '''</summary>
        Friend ReadOnly Property Text_Fields() As String
            Get
                Return ResourceManager.GetString("Text_Fields", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на TxtPinX,TxtPinY,TxtWidth,TxtHeight,TxtLocPinX,TxtLocPinY,TxtAngle.
        '''</summary>
        Friend ReadOnly Property Text_Transform() As String
            Get
                Return ResourceManager.GetString("Text_Transform", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на ColorSchemeIndex,EffectSchemeIndex,ConnectorSchemeIndex,FontSchemeIndex,ThemeIndex,VariationColorIndex,VariationStyleIndex,EmbellishmentIndex.
        '''</summary>
        Friend ReadOnly Property Theme_Properties() As String
            Get
                Return ResourceManager.GetString("Theme_Properties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на User.Row_1.Value,User.Row_1.Prompt.
        '''</summary>
        Friend ReadOnly Property User_Defined_Cells() As String
            Get
                Return ResourceManager.GetString("User_Defined_Cells", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Типы объектов,Слой,Имя мастера,Имя фигуры,ID фигуры,Текст,Стиль текста,Стиль линии,Стиль заливки,Длина,Периметр,Площадь,Положение X,Положение Y,Начало X,Начало Y,Конец X,Конец Y,Угол,Ширина,Высота,Тип линии,Тип заливки,Толщина линии,Сглаживание угла,Цвет заливки,Цвет линии,Цвет шрифта,Размер шрифта,Шрифт,Количество субфигур,Data123,Shapesheet.
        '''</summary>
        Friend ReadOnly Property Все_объекты() As String
            Get
                Return ResourceManager.GetString("Все_объекты", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на 6,8,9,10,11,12,14,16,18,24,30,36,48,60.
        '''</summary>
        Friend ReadOnly Property Размер_шрифта() As String
            Get
                Return ResourceManager.GetString("Размер_шрифта", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Простая фигура,Одномерная фигура,Коннектор,Сгруппированная фигура,Надпись,Выноска,Размер,Контейнер,Направляющая,Растровый рисунок,Метафайл,Объект OLE,Рукописный объект.
        '''</summary>
        Friend ReadOnly Property Типы_объектов() As String
            Get
                Return ResourceManager.GetString("Типы_объектов", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
